<?php

namespace Alghobary\LaravelMacros\Macros;

use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Support\Str;

class BuilderMacros
{
    public static function register()
    {
        /**
         * Add 'getSql' method to both database query builder and eloquent query builder,
         * this method will return the sql code generated by the builder just like 'toSql' does,
         * but with the actual values instead of '?' placeholders
         */
        QueryBuilder::macro('getSql', function () {
            $bindings = collect($this->getBindings())
                ->map(fn ($val) => "'$val'")
                ->toArray();

            return Str::replaceArray('?', $bindings, $this->toSql());
        });

        EloquentBuilder::macro('getSql', function () {
            $bindings = collect($this->getBindings())
                ->map(fn ($val) => "'$val'")
                ->toArray();

            return Str::replaceArray('?', $bindings, $this->toSql());
        });
    }
}
